### ISSUE TITLE
Can't make iOS receive NearBy message from BLE but can receive from ultrasonic

### ISSUE THREAD

**Issue by nattaponasa** [googlesamples/ios-nearby#10]
Hi ,

I've clone the sample code of both iOS and Android repo, but I cannot make both device communicate with each other on BLE channel. I've found thread about iOS-Android communication [issue](https://github.com/googlesamples/ios-nearby/issues/4) ,and tried the same suggestion of adding a message type, but it didn't work for me.

**Key configuration**:
- both iOS and Android credential are configured in Nearby API credential

**Audio Channel**(allow only audio):
- iOS-iOS and Android-Android work perfectly
- Android <-> iOS work perfectly

**BLE Channel**(allow only BLE):
- iOS-iOS and Android-Android work perfectly
- Android app **doesn't receive** messages from iOS app
- iOS app **doesn't receive** messages from Android app.

**Audio and BLE Channel** (allow both channel):
- iOS-iOS and Android-Android only work perfectly fine
- iOS <-> Android work when both device are within 1.5 metre range (I think only audio do the work)

**Devices:**
1. iPhone 6s plus (iOS 9.2.1)
2. Samsung Galaxy S7 edge (6.0.1)
3. Samsung Galaxy Tab A 9.7 (5.0.2)

**Comment by dan-webb** [comment]
Thanks for reporting this BLE bug.  A bug fix will be released soon.
