### ISSUE TITLE
pod installs 0.9.5

### ISSUE THREAD

**Issue by kiranmadhav** [googlesamples/ios-nearby#14]
Please help me how to install version 1.0.1

I tried the following

pod 'NearbyMessages', '~> 1.0'

**Comment by dan-webb** [comment]
Try deleting the `Pods` directory and running `pod install` again.

I've heard of one other customer running into this problem, but I'm not able to reproduce it.  It seems to be a bug in CocoaPods.

**Comment by kiranmadhav** [comment]
Thanks for the support.

I have tried deleting the pods. No Luck

At last I made it work by downloading the corresponding version and installed the pod manually.
