### ISSUE TITLE
obj-c sample project cannot use "-all_load" Other Linker Flags.

### ISSUE THREAD

**Issue by ysmdsty** [googlesamples/ios-nearby#3]
We tried to use the "-all_load" Other Linker Flags on "obj-c sample project".
But build error occurred.
Error message is "ld: 34 duplicate symbols for architecture x86_64".

one of 34 duplicate symbol error is following.

```
duplicate symbol
__ZNK16audio_whispernet17WhispernetDecoder35ComputePostprocessAcquisitionScoresERKN5Eigen3MapIKNS1_6MatrixIfLin1ELi1ELi0ELin1ELi1EEELi0ENS1_6StrideILi0ELi0EEEEEPNSt3__16vectorIfNSB_9allocatorIfEEEE in:
.../libGNSMessages.a(whispernet_decoder.o)
```

Our project needs "-all_load" Other Linker Flags.
So our project meets this error also.

If you know good solution, please tell us.

thank you.

**Comment by dan-webb** [comment]
Thank you for the bug report.  I've found and fixed the problem, and the fix will be in the next release of Nearby Messages.  Unfortunately, I don't know of a workaround for you until you pick up the next release.

**Comment by ysmdsty** [comment]
@dan-webb 
Thank you for problem fix.
We wait next release, and will pick up next release.

Thanks so much.

**Comment by ysmdsty** [comment]
By using NearbyMessages 0.10.0, we could use the "-all_load" Other Linker Flags on "obj-c sample project".
Thank you :bow:
